name: Build Geode Mod

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y cmake ninja-build git

      - name: Clone Geode SDK
        run: |
          git clone --depth=1 https://github.com/geode-sdk/geode.git
          mkdir build && cd build
          cmake .. -G Ninja -DGEODE_SDK=$(pwd)/../geode
          ninja

      - name: Upload built mod
        uses: actions/upload-artifact@v4
        with:
          name: disable-glow-mod
          path: build/*.geode