name: Build Geode Mod

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout your mod repo
        uses: actions/checkout@v4

      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake ninja-build git

      - name: Clone Geode SDK
        run: |
          git clone --depth=1 https://github.com/geode-sdk/geode.git ../geode

      - name: Build mod
        run: |
          mkdir build
          cd build
          cmake .. -G Ninja -DGEODE_SDK="${{ github.workspace }}/../geode"
          ninja

      - name: Upload built mod
        uses: actions/upload-artifact@v4
        with:
          name: disable-glow-mod
          path: build/*.geode